AWSTemplateFormatVersion: 2010-09-09
Description: Creates the VHP environment

Parameters:
  keypairName: ./resources/parameters/keypairName.yml
  instanceType: ./resources/parameters/instanceType.yml
  environment: ./resources/parameters/environment.yml
  #elasticIP: ./resources/parameters/elasticIP.yml

Mappings:
  amiMap: !include ./resources/parameters/amiMap.yml

Resources:
  vhpVPC: !include ./resources/VPC/vhpVPC.yml

  publicSubnet: !include ./resources/VPC/publicSubnet.yml
  privateSubnet: !include ./resources/VPC/privateSubnet.yml

  vhpInternetGateway: ./resources/VPC/vhpInternetGateway.yml
  GatewayToInternet: ./resources/VPC/GatewayToInternet.yml
  publicRouteTable: ./resources/VPC/publicRouteTable.yml
  publicRoute: ./resources/VPC/publicRoute.yml
  publicSubnetRouteTableAssociation: ./resources/VPC/publicSubnetRouteTableAssociation.yml

  vhpNatGateway: ./resources/VPC/vhpNatGateway.yml
  NatPublicIP: ./resources/VPC/NatPublicIP.yml
  privateRouteTable: ./resources/VPC/privateRouteTable.yml
  privateRoute: ./resources/VPC/privateRoute.yml
  privateSubnetRouteTableAssociation: ./resources/VPC/privateSubnetRouteTableAssociation.yml

  #elasticIPassociation: ./resources/VPC/elasticIPassociation.yml

  instanceRole: ./resources/IAM/instanceRole.yml
  instanceProfile: ./resources/IAM/instanceProfile.yml
  devEmailsTopic: ./resources/SNS/devEmailsTopic.yml

  bastionHostSecurityGroup: ./resources/bastion/bastionHostSecurityGroup.yml
  bastionHostLaunchTemplate: ./resources/bastion/bastionHostLaunchTemplate.yml
  bastionHostEC2: ./resources/bastion/bastionHostEC2.yml

  ppSecurityGroup: ./resources/pp/ppSecurityGroup.yml
  ppLaunchTemplate: ./resources/pp/ppLaunchTemplate.yml
  ppEC2Instance: ./resources/pp/ppEC2Instance.yml
  ppCPUAlarm: ./resources/pp/ppCPUAlarm.yml
  ppStatusCheckFailedAlarm: ./resources/pp/ppStatusCheckFailedAlarm.yml

  webserverSecurityGroup: ./resources/webserver/webserverSecurityGroup.yml
  webserverLaunchTemplate: ./resources/webserver/webserverLaunchTemplate.yml
  webserverEC2Instance: ./resources/webserver/webserverEC2Instance.yml
  webserverCPUAlarm: ./resources/webserver/webserverCPUAlarm.yml
  webserverStatusCheckFailedAlarm: ./resources/webserver/webserverStatusCheckFailedAlarm.yml

  coreSecurityGroup: ./resources/core/coreSecurityGroup.yml
  coreLaunchTemplate: ./resources/core/coreLaunchTemplate.yml
  coreEC2Instance: ./resources/core/coreEC2Instance.yml
  coreCPUAlarm: ./resources/core/coreCPUAlarm.yml
  coreStatusCheckFailedAlarm: ./resources/core/coreStatusCheckFailedAlarm.yml

  martSecurityGroup: ./resources/mart/martSecurityGroup.yml
  martLaunchTemplate: ./resources/mart/martLaunchTemplate.yml
  martEC2Instance: ./resources/mart/martEC2Instance.yml
  martCPUAlarm: ./resources/mart/martCPUAlarm.yml
  martStatusCheckFailedAlarm: ./resources/mart/martStatusCheckFailedAlarm.yml

  servicesSecurityGroup: ./resources/services/servicesSecurityGroup.yml
  servicesLaunchTemplate: ./resources/services/servicesLaunchTemplate.yml
  servicesEC2Instance: ./resources/services/servicesEC2Instance.yml
  servicesCPUAlarm: ./resources/services/servicesCPUAlarm.yml
  servicesStatusCheckFailedAlarm: ./resources/services/servicesStatusCheckFailedAlarm.yml
  
Outputs:
  launchTemplateOutputIDs: ./resources/outputs/launchTemplateOutputIDs.yml

