
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - bastionHostLaunchTemplate
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref bastionHostLaunchTemplate
        Version: !GetAtt bastionHostLaunchTemplate.DefaultVersionNumber