
    Type: 'AWS::EC2::LaunchTemplate'
    DependsOn:
      - instanceProfile
      - bastionHostSecurityGroup
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              Iops: 3000
              Throughput: 125
              VolumeSize: 8
              VolumeType: gp3
        EbsOptimized: true
        IamInstanceProfile:
          Arn: !GetAtt instanceProfile.Arn
        KeyName: !Ref keypairName
        UserData: !Base64 '80'
        ImageId: !FindInMap 
          - amiMap
          - !Ref 'AWS::Region'
          - bastionHostAmiId
        #ImageId: ami-036538d509a244cf1
        InstanceType: !Ref instanceType
        NetworkInterfaces:
        - DeviceIndex: 0
          PrivateIpAddress: 10.0.1.15
          SubnetId: !Ref publicSubnet
          Groups:
            - !Ref bastionHostSecurityGroup
        MetadataOptions:
          HttpTokens: required
        Monitoring:
          Enabled: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${environment}-vhp-bastion-host'
              - Key: environment
                Value: !Ref environment
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: environment
              Value: !Ref environment
  bastionHostEC2:
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - bastionHostLaunchTemplate
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref bastionHostLaunchTemplate
        Version: !GetAtt bastionHostLaunchTemplate.DefaultVersionNumber