
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - servicesLaunchTemplate
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref servicesLaunchTemplate
        Version: !GetAtt servicesLaunchTemplate.DefaultVersionNumber
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: Name
          Value: !Sub '${environment}-vhp-services'