
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref vhpVPC
      #AvailabilityZone: us-east-2a
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${environment}-privateSubnet'
    DependsOn:
      - vhpVPC
      ## NAT GATEWAY
  vhpNatGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: NatPublicIP
    Properties: 
      SubnetId: !Ref publicSubnet
      AllocationId: !GetAtt NatPublicIP.AllocationId
      Tags:
        - Key: Name
          Value: !Sub '${environment}-natGateway'
      ## ELASTIC IP
  NatPublicIP:
    Type: AWS::EC2::EIP
    DependsOn: vhpVPC
    Properties:
      Domain: vpc
  privateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref vhpVPC
      Tags:
        - Key: Name
          Value: !Sub '${environment}-privateRouteTable'
  privateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref privateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref vhpNatGateway # this will eventually be a NAT gateway
    DependsOn:
      - GatewayToInternet
  privateSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref privateSubnet
      RouteTableId: !Ref privateRouteTable