
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref vhpVPC
      #AvailabilityZone: us-east-2a
      CidrBlock: 10.0.1.0/24
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${environment}-publicSubnet'
    DependsOn:
      - vhpVPC
