
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - webserverLaunchTemplate
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref webserverLaunchTemplate
        Version: !GetAtt webserverLaunchTemplate.DefaultVersionNumber