
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - webserverLaunchTemplate
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref webserverLaunchTemplate
        Version: !GetAtt webserverLaunchTemplate.DefaultVersionNumber
      ImageId: !FindInMap
        - amiMap
        - !Ref 'AWS::Region'
        - webserverAmiId
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: Name
          Value: !Sub '${environment}-vhp-webserver'