
    Type: 'AWS::EC2::SecurityGroup'
    DependsOn:
      - webserverSecurityGroup
    Properties:
      GroupDescription: allows ssh from vogel network
      GroupName: vhp-core-sg 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt webserverSecurityGroup.GroupId
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !GetAtt bastionHostSecurityGroup.GroupId
        - IpProtocol: tcp
          FromPort: 6000
          ToPort: 6000
          SourceSecurityGroupId: !GetAtt bastionHostSecurityGroup.GroupId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 9000
          ToPort: 9000
          CidrIp: 0.0.0.0/0
          Description: change source to services sg
        - IpProtocol: tcp
          FromPort: 9001
          ToPort: 9001
          CidrIp: 0.0.0.0/0
          Description: change source to services sg
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: change source to mart sg
      VpcId: !Ref vhpVPC
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: Name
          Value: !Sub '${environment}-core-sg'