
    Type: 'AWS::EC2::LaunchTemplate'
    DependsOn:
      - instanceProfile
      - coreSecurityGroup
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              Iops: 3000
              Throughput: 125
              VolumeSize: 8
              VolumeType: gp3
        EbsOptimized: true
        IamInstanceProfile:
          Arn: !GetAtt instanceProfile.Arn
        KeyName: !Ref keypairName
        UserData: !Base64 '80'
        ImageId: !FindInMap 
          - amiMap
          - !Ref 'AWS::Region'
          - coreAmiId
        #ImageId: ami-03127faf27ba03011
        InstanceType: !Ref instanceType
        NetworkInterfaces:
        - DeviceIndex: 0
          PrivateIpAddress: 10.0.2.212
          SubnetId: !Ref privateSubnet 
          Groups:
            - !Ref coreSecurityGroup
          AssociatePublicIpAddress: false
        MetadataOptions:
          HttpTokens: required
        Monitoring:
          Enabled: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${environment}-vhp-core'
              - Key: environment
                Value: !Ref environment
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: environment
              Value: !Ref environment
  coreEC2Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - coreLaunchTemplate
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref coreLaunchTemplate
        Version: !GetAtt coreLaunchTemplate.DefaultVersionNumber