
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - coreLaunchTemplate
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref coreLaunchTemplate
        Version: !GetAtt coreLaunchTemplate.DefaultVersionNumber
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: Name
          Value: !Sub '${environment}-vhp-core'